### ISSUE TITLE
Erro ao tentar executar

### ISSUE THREAD

**Issue by PatrickZerbinatti** [siga0984/NETiZAP#1]
Adicionei no menu e tentei executar.

![image](https://user-images.githubusercontent.com/33162950/72622609-57077800-3922-11ea-82d7-38e48dbb7bd4.png)

Sabe por que?

**Comment by siga0984** [comment]
Fala campeão, beleza ?

Este programa de exemplo usa uma TWINDOW() - Janela Principal do AdvPL -- e
por isso somente pode ser executado "diretamente" pelo SmartClient !! Para rodar ele de dentro do Menu do ERP, é necessário alterar o programa para criar uma DIALOG ao invés de uma WINDOW !! Estou fazendo isso neste instante, basta pegar a nova versão após eu fazer o COMMIT

*Abraços Júlio Wittwer*
siga0984@gmail.com
https://siga0984.wordpress.com/
https://www.facebook.com/siga0984

**Comment by siga0984** [comment]
Pronto ! Agora o programa usa uma DIALOG -- Basta baixar novamente a versão atualizada :D
